import type { CurriculumModule } from './types'

/**
 * Complete ACC × Sprints — Flutter Bootcamp curriculum
 * 5 sprints | 34 modules | ~400 lesson items | ~66h 43m total
 */
export const CURRICULUM: CurriculumModule[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // SPRINT 1 — Engineering Foundations (22h 55m) | Systems Track
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 's1_onboarding',
    sprint: 1,
    sprintName: 'Engineering Foundations',
    track: 'Systems',
    title: 'Welcome to Sprints & Onboarding',
    totalTopicsCount: 3,
    totalDurationText: '5m',
    isTask: false,
    isCapstone: false,
    badges: ['micro-learning'],
    lessons: [
      { id: 's1_onb_01', title: 'Welcome to the ACC × Sprints Bootcamp', duration: '2m 50s', type: 'video' },
      { id: 's1_onb_02', title: 'How to Navigate the Learning Platform', duration: '1m 24s', type: 'video' },
      { id: 's1_onb_03', title: 'Bootcamp Roadmap & Sprint Overview', duration: '24s', type: 'capsule' },
    ],
  },

  {
    id: 's1_se_intro',
    sprint: 1,
    sprintName: 'Engineering Foundations',
    track: 'Systems',
    title: 'Software Engineering',
    totalTopicsCount: 41,
    totalDurationText: '3h 40m',
    taskName: 'Architect a Portfolio Website with UML & SDLC',
    isTask: true,
    isCapstone: false,
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's1_se_01', title: 'Why Software Engineering Matters', duration: '4m 16s', type: 'video' },
      { id: 's1_se_02', title: 'The 5 Characteristics of Good Software', duration: '6m 30s', type: 'video' },
      { id: 's1_se_03', title: 'SDLC Overview — Planning to Maintenance', duration: '8m 15s', type: 'video' },
      { id: 's1_se_04', title: 'Waterfall Model — Phases & Limitations', duration: '10m 45s', type: 'video' },
      { id: 's1_se_05', title: 'V-Model — Verification & Validation', duration: '9m 20s', type: 'video' },
      { id: 's1_se_06', title: 'Iterative & Incremental Development', duration: '7m 10s', type: 'video' },
      { id: 's1_se_07', title: 'Software Design: Cohesion vs Coupling', duration: '11m 00s', type: 'video' },
      { id: 's1_se_08', title: 'Understanding APIs & REST Contracts', duration: '7m 45s', type: 'video' },
      { id: 's1_se_09', title: 'UML Class Diagrams', duration: '12m 30s', type: 'video' },
      { id: 's1_se_10', title: 'Use Case Diagrams', duration: '8m 00s', type: 'video' },
      { id: 's1_se_11', title: 'Sequence & Activity Diagrams', duration: '10m 15s', type: 'video' },
      { id: 's1_se_12', title: 'Flowcharts & System Architecture Diagrams', duration: '9m 30s', type: 'video' },
      { id: 's1_se_q1', title: 'Quiz: SDLC & Software Characteristics', duration: '5m', type: 'quiz' },
      { id: 's1_se_t1', title: 'Task: Architect a Portfolio Website with UML & SDLC', type: 'task' },
    ],
  },

  {
    id: 's1_scm_git',
    sprint: 1,
    sprintName: 'Engineering Foundations',
    track: 'Systems',
    title: 'Software Configuration Management & Git VCS',
    totalTopicsCount: 24,
    totalDurationText: '2h 10m',
    taskName: 'Build a Portfolio with Git & GitHub',
    isTask: true,
    isCapstone: false,
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's1_git_01', title: 'What is Software Configuration Management?', duration: '5m 20s', type: 'video' },
      { id: 's1_git_02', title: 'Git Internals — Blobs, Trees & Commits', duration: '9m 45s', type: 'video' },
      { id: 's1_git_03', title: 'Git Init, Add, Commit & Status', duration: '8m 30s', type: 'video' },
      { id: 's1_git_04', title: 'Working with Remote Repos — GitHub SSH Setup', duration: '10m 00s', type: 'video' },
      { id: 's1_git_05', title: 'Branching Strategies — Feature & GitFlow', duration: '11m 15s', type: 'video' },
      { id: 's1_git_06', title: 'Merging & Merge Conflict Resolution', duration: '12m 30s', type: 'video' },
      { id: 's1_git_07', title: 'Pull Requests & Code Review Workflow', duration: '8m 00s', type: 'video' },
      { id: 's1_git_08', title: 'Rebase vs Merge — When to Use Each', duration: '9m 20s', type: 'video' },
      { id: 's1_git_09', title: '.gitignore, Tags & Semantic Versioning', duration: '6m 45s', type: 'video' },
      { id: 's1_git_q1', title: 'Quiz: Git Workflow Fundamentals', duration: '5m', type: 'quiz' },
      { id: 's1_git_t1', title: 'Task: Build a Portfolio with Git & GitHub', type: 'task' },
    ],
  },

  {
    id: 's1_db_intro',
    sprint: 1,
    sprintName: 'Engineering Foundations',
    track: 'Systems',
    title: 'Introduction to Database Management',
    totalTopicsCount: 53,
    totalDurationText: '4h 20m',
    taskName: 'Design the Dot Bookstore Database — ERD & Data Modelling',
    isTask: true,
    isCapstone: false,
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's1_db_01', title: 'What is a Database? DBMS Types Overview', duration: '6m 10s', type: 'video' },
      { id: 's1_db_02', title: 'RDBMS vs NoSQL — Trade-offs & Use Cases', duration: '9m 45s', type: 'video' },
      { id: 's1_db_03', title: 'ACID Properties & Database Transactions', duration: '8m 30s', type: 'video' },
      { id: 's1_db_04', title: 'Entities, Attributes & Relationships', duration: '7m 20s', type: 'video' },
      { id: 's1_db_05', title: 'ERD Notation — Chen & Crow\'s Foot', duration: '10m 00s', type: 'video' },
      { id: 's1_db_06', title: 'Cardinality — 1:1, 1:N, M:N Relationships', duration: '8m 15s', type: 'video' },
      { id: 's1_db_07', title: 'Functional Dependencies & Anomalies', duration: '9m 00s', type: 'video' },
      { id: 's1_db_08', title: '1NF — Atomic Values & No Repeating Groups', duration: '7m 30s', type: 'video' },
      { id: 's1_db_09', title: '2NF — Full Functional Dependency', duration: '8m 45s', type: 'video' },
      { id: 's1_db_10', title: '3NF & BCNF — Eliminating Transitive Dependencies', duration: '10m 20s', type: 'video' },
      { id: 's1_db_11', title: 'Lab: ERD Design — University System', duration: '45m', type: 'lab' },
      { id: 's1_db_12', title: 'Lab: Normalize a Messy Spreadsheet to 3NF', duration: '40m', type: 'lab' },
      { id: 's1_db_13', title: 'Lab: Design the Bookstore ERD', duration: '35m', type: 'lab' },
      { id: 's1_db_q1', title: 'Quiz: Normalization & ERD Design', duration: '8m', type: 'quiz' },
      { id: 's1_db_t1', title: 'Task: Design the Dot Bookstore Database — ERD & Data Modelling', type: 'task' },
    ],
  },

  {
    id: 's1_rdb_concepts',
    sprint: 1,
    sprintName: 'Engineering Foundations',
    track: 'Systems',
    title: 'Relational Database Concepts & PostgreSQL Setup',
    totalTopicsCount: 24,
    totalDurationText: '2h 05m',
    taskName: 'Enforce Data Integrity with Custom PostgreSQL Domains',
    isTask: true,
    isCapstone: false,
    prerequisites: ['s1_db_intro'],
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's1_rdb_01', title: 'Installing PostgreSQL & pgAdmin on Windows', duration: '8m 30s', type: 'video' },
      { id: 's1_rdb_02', title: 'pgAdmin Interface Tour & Database Creation', duration: '6m 15s', type: 'video' },
      { id: 's1_rdb_03', title: 'DDL — CREATE TABLE, Data Types & Constraints', duration: '11m 00s', type: 'video' },
      { id: 's1_rdb_04', title: 'PRIMARY KEY, FOREIGN KEY & UNIQUE Constraints', duration: '9m 45s', type: 'video' },
      { id: 's1_rdb_05', title: 'CHECK Constraints & NOT NULL', duration: '7m 20s', type: 'video' },
      { id: 's1_rdb_06', title: 'Custom DOMAIN Types in PostgreSQL', duration: '8m 00s', type: 'video' },
      { id: 's1_rdb_07', title: 'Sequences, SERIAL & Auto-Increment', duration: '6m 30s', type: 'video' },
      { id: 's1_rdb_08', title: 'ALTER TABLE & Modifying Existing Schema', duration: '7m 15s', type: 'video' },
      { id: 's1_rdb_09', title: 'Converting ERD Scenario to Relational Schema', duration: '10m 45s', type: 'video' },
      { id: 's1_rdb_q1', title: 'Quiz: PostgreSQL Setup & Data Integrity', duration: '5m', type: 'quiz' },
      { id: 's1_rdb_t1', title: 'Task: Enforce Data Integrity with Custom PostgreSQL Domains', type: 'task' },
    ],
  },

  {
    id: 's1_sql_basics',
    sprint: 1,
    sprintName: 'Engineering Foundations',
    track: 'Systems',
    title: 'SQL Basics',
    totalTopicsCount: 32,
    totalDurationText: '2h 50m',
    taskName: 'Logistics Module Database Initialization & Seeding',
    isTask: true,
    isCapstone: false,
    prerequisites: ['s1_db_intro'],
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's1_sql_01', title: 'SQL vs NoSQL — When to Use What', duration: '5m 30s', type: 'video' },
      { id: 's1_sql_02', title: 'DDL — CREATE, ALTER, DROP, TRUNCATE', duration: '9m 00s', type: 'video' },
      { id: 's1_sql_03', title: 'DML — INSERT, UPDATE, DELETE', duration: '8m 45s', type: 'video' },
      { id: 's1_sql_04', title: 'SELECT & Filtering with WHERE', duration: '7m 20s', type: 'video' },
      { id: 's1_sql_05', title: 'ILIKE, IN, BETWEEN, IS NULL', duration: '6m 30s', type: 'video' },
      { id: 's1_sql_06', title: 'Aggregations — COUNT, SUM, AVG, MIN, MAX', duration: '8m 00s', type: 'video' },
      { id: 's1_sql_07', title: 'GROUP BY, HAVING & DISTINCT', duration: '9m 15s', type: 'video' },
      { id: 's1_sql_08', title: 'ORDER BY, LIMIT & OFFSET (Pagination)', duration: '6m 45s', type: 'video' },
      { id: 's1_sql_09', title: 'INNER JOIN — Combining Related Tables', duration: '10m 00s', type: 'video' },
      { id: 's1_sql_10', title: 'LEFT, RIGHT & FULL OUTER JOINs', duration: '11m 30s', type: 'video' },
      { id: 's1_sql_11', title: 'SELF JOIN & CROSS JOIN', duration: '8m 15s', type: 'video' },
      { id: 's1_sql_q1', title: 'Quiz: SQL Fundamentals', duration: '8m', type: 'quiz' },
      { id: 's1_sql_t1', title: 'Task: Logistics Module Database Initialization & Seeding', type: 'task' },
    ],
  },

  {
    id: 's1_linux_intro',
    sprint: 1,
    sprintName: 'Engineering Foundations',
    track: 'Systems',
    title: 'Linux History and Essential Commands',
    totalTopicsCount: 22,
    totalDurationText: '1h 55m',
    taskName: 'Day One Linux Practice in WSL: Navigation and File Management',
    isTask: true,
    isCapstone: false,
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's1_lnx_01', title: 'Linux History & UNIX Philosophy', duration: '5m 45s', type: 'video' },
      { id: 's1_lnx_02', title: 'Installing WSL on Windows', duration: '7m 30s', type: 'video' },
      { id: 's1_lnx_03', title: 'Linux Filesystem Hierarchy — FHS Standard', duration: '8m 00s', type: 'video' },
      { id: 's1_lnx_04', title: 'Navigation — pwd, ls, cd, tree', duration: '6m 15s', type: 'video' },
      { id: 's1_lnx_05', title: 'File Operations — cp, mv, rm, mkdir, touch', duration: '7m 30s', type: 'video' },
      { id: 's1_lnx_06', title: 'Reading Files — cat, less, head, tail', duration: '6m 00s', type: 'video' },
      { id: 's1_lnx_07', title: 'File Permissions — chmod, chown, chgrp', duration: '9m 45s', type: 'video' },
      { id: 's1_lnx_08', title: 'Lab: M45T3R — Linux Navigation Challenge', duration: '25m', type: 'lab' },
      { id: 's1_lnx_09', title: 'Lab: D15C0v3ry — File System Exploration', duration: '20m', type: 'lab' },
      { id: 's1_lnx_t1', title: 'Task: Day One Linux Practice in WSL', type: 'task' },
    ],
  },

  {
    id: 's1_linux_ops',
    sprint: 1,
    sprintName: 'Engineering Foundations',
    track: 'Systems',
    title: 'Linux Basic Operations',
    totalTopicsCount: 26,
    totalDurationText: '2h 20m',
    taskName: 'Advanced Log Parsing: Extracting Flags via Pipeline',
    isTask: true,
    isCapstone: false,
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's1_ops_01', title: 'Terminal Shortcuts & History Navigation', duration: '5m 00s', type: 'video' },
      { id: 's1_ops_02', title: 'Pipes & Redirection — |, >, >>, 2>', duration: '8m 30s', type: 'video' },
      { id: 's1_ops_03', title: 'Text Processing — grep, awk, sed', duration: '12m 00s', type: 'video' },
      { id: 's1_ops_04', title: 'Process Management — ps, top, htop, kill', duration: '9m 15s', type: 'video' },
      { id: 's1_ops_05', title: 'Environment Variables & .bashrc', duration: '7m 00s', type: 'video' },
      { id: 's1_ops_06', title: 'Bash Scripting — Variables, Loops & Conditionals', duration: '14m 30s', type: 'video' },
      { id: 's1_ops_07', title: 'Cron Jobs — Scheduling Tasks', duration: '7m 45s', type: 'video' },
      { id: 's1_ops_08', title: 'Lab: Grep Master — Pattern Matching Challenge', duration: '30m', type: 'lab' },
      { id: 's1_ops_09', title: 'Lab: Bash Legend — Automation Script Challenge', duration: '25m', type: 'lab' },
      { id: 's1_ops_t1', title: 'Task: Advanced Log Parsing: Extracting Flags via Pipeline', type: 'task' },
    ],
  },

  {
    id: 's1_networks_intro',
    sprint: 1,
    sprintName: 'Engineering Foundations',
    track: 'Systems',
    title: 'Introduction to Computer Networks',
    totalTopicsCount: 92,
    totalDurationText: '5h 30m',
    taskName: 'Build, Test, and Analyze a Small Network',
    isTask: true,
    isCapstone: false,
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's1_net_01', title: 'Network Types — LAN, WAN, MAN, PAN', duration: '6m 00s', type: 'video' },
      { id: 's1_net_02', title: 'NIC, MAC Addresses & Physical Topology', duration: '8m 30s', type: 'video' },
      { id: 's1_net_03', title: 'IP Addressing — IPv4 Classes & CIDR Notation', duration: '11m 00s', type: 'video' },
      { id: 's1_net_04', title: 'Hubs, Switches & Routers — Differences & Use', duration: '9m 45s', type: 'video' },
      { id: 's1_net_05', title: 'Firewalls & Network Security Fundamentals', duration: '8m 15s', type: 'video' },
      { id: 's1_net_06', title: 'OSI Model — 7 Layers Explained', duration: '14m 30s', type: 'video' },
      { id: 's1_net_07', title: 'TCP/IP Protocol Suite & Comparison to OSI', duration: '10m 00s', type: 'video' },
      { id: 's1_net_08', title: 'HTTP & HTTPS — Request/Response Lifecycle', duration: '9m 15s', type: 'video' },
      { id: 's1_net_09', title: 'DNS — How Domain Resolution Works', duration: '8m 00s', type: 'video' },
      { id: 's1_net_10', title: 'DHCP — Dynamic IP Assignment', duration: '6m 30s', type: 'video' },
      { id: 's1_net_11', title: 'Binary & Hex Number Systems for Networking', duration: '10m 45s', type: 'video' },
      { id: 's1_net_12', title: 'Wireshark GUI — Capturing & Filtering Packets', duration: '15m 00s', type: 'video' },
      { id: 's1_net_13', title: 'tcpdump — CLI Packet Analysis', duration: '9m 30s', type: 'video' },
      { id: 's1_net_14', title: 'Analyzing HTTP, DNS & TCP Traffic in Wireshark', duration: '12m 00s', type: 'lab' },
      { id: 's1_net_q1', title: 'Quiz: OSI Layers & Network Fundamentals', duration: '10m', type: 'quiz' },
      { id: 's1_net_t1', title: 'Task: Build, Test, and Analyze a Small Network', type: 'task' },
    ],
  },

  {
    id: 's1_network_ports',
    sprint: 1,
    sprintName: 'Engineering Foundations',
    track: 'Systems',
    title: 'Network Ports & Connectivity',
    totalTopicsCount: 44,
    totalDurationText: '3h 15m',
    taskName: 'Subnetting, Protocols, Ports, and Connectivity Troubleshooting Lab',
    isTask: true,
    isCapstone: false,
    prerequisites: ['s1_networks_intro'],
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's1_prt_01', title: 'Subnetting — Dividing IP Address Spaces', duration: '12m 30s', type: 'video' },
      { id: 's1_prt_02', title: 'Subnet Mask Calculation & CIDR Practice', duration: '10m 00s', type: 'video' },
      { id: 's1_prt_03', title: 'TCP vs UDP — When to Use Each', duration: '8m 15s', type: 'video' },
      { id: 's1_prt_04', title: 'ARP, DNS & SSH Protocols Deep Dive', duration: '9m 45s', type: 'video' },
      { id: 's1_prt_05', title: 'Well-Known, Registered & Dynamic Port Ranges', duration: '7m 00s', type: 'video' },
      { id: 's1_prt_06', title: 'NAT & Port Forwarding Explained', duration: '9m 30s', type: 'video' },
      { id: 's1_prt_07', title: 'Routing Protocols — Static vs Dynamic', duration: '8m 00s', type: 'video' },
      { id: 's1_prt_08', title: 'Netcat — The Swiss Army Knife for Networks', duration: '10m 15s', type: 'video' },
      { id: 's1_prt_09', title: 'ping, traceroute & nmap for Troubleshooting', duration: '11m 00s', type: 'video' },
      { id: 's1_prt_10', title: 'Lab: Netcat Port Scanning & Banner Grabbing', duration: '30m', type: 'lab' },
      { id: 's1_prt_q1', title: 'Quiz: Ports, Subnetting & Protocols', duration: '8m', type: 'quiz' },
      { id: 's1_prt_t1', title: 'Task: Subnetting, Protocols, Ports & Connectivity Troubleshooting Lab', type: 'task' },
    ],
  },

  {
    id: 's1_capstone',
    sprint: 1,
    sprintName: 'Engineering Foundations',
    track: 'Systems',
    title: '🏆 Capstone: IT Support & Network Troubleshooting System',
    totalTopicsCount: 5,
    totalDurationText: '8h',
    isTask: false,
    isCapstone: true,
    badges: ['capstone', 'high-energy'],
    lessons: [
      { id: 's1_cap_01', title: 'Capstone Brief & Requirements Review', duration: '15m', type: 'video' },
      { id: 's1_cap_02', title: 'Design the IT Support Database Schema', type: 'lab' },
      { id: 's1_cap_03', title: 'Network Topology Design & Subnetting', type: 'lab' },
      { id: 's1_cap_04', title: 'Traffic Analysis & Incident Report', type: 'lab' },
      { id: 's1_cap_05', title: 'Final Submission & Peer Review', type: 'capstone' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPRINT 2 — Flutter Development Essentials (12h 24m)
  // Design Track modules first, then Mobile Track
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 's2_ux_foundations',
    sprint: 2,
    sprintName: 'Flutter Development Essentials',
    track: 'Quality',
    title: 'Foundations of UX Design',
    totalTopicsCount: 57,
    totalDurationText: '2h 45m',
    taskName: 'Redesigning LinkedIn\'s Sign-Up Experience — End to End',
    isTask: true,
    isCapstone: false,
    badges: ['task-required', 'micro-learning'],
    lessons: [
      { id: 's2_ux_01', title: 'What is UX? Human-Centered Design Principles', duration: '6m 30s', type: 'video' },
      { id: 's2_ux_02', title: 'The Double Diamond Model — Discover → Deliver', duration: '8m 45s', type: 'video' },
      { id: 's2_ux_03', title: 'Empathy Mapping & User Research Methods', duration: '10m 00s', type: 'video' },
      { id: 's2_ux_04', title: 'User Interviews — Planning & Execution', duration: '9m 15s', type: 'video' },
      { id: 's2_ux_05', title: 'Problem Framing & HMW (How Might We) Questions', duration: '7m 00s', type: 'video' },
      { id: 's2_ux_06', title: 'WCAG 2.1 — POUR Principles & Accessibility Audit', duration: '11m 30s', type: 'video' },
      { id: 's2_ux_07', title: 'Contrast Ratios, Alt Text & ARIA Roles', duration: '8m 00s', type: 'video' },
      { id: 's2_ux_08', title: 'Google Design Sprint — 5 Phases in 5 Days', duration: '10m 45s', type: 'video' },
      { id: 's2_ux_09', title: 'Value Proposition Canvas — Customer vs Company', duration: '9m 30s', type: 'video' },
      { id: 's2_ux_10', title: 'Usability Testing — Planning & Metrics', duration: '8m 15s', type: 'video' },
      { id: 's2_ux_q1', title: 'Quiz: UX Fundamentals & WCAG', duration: '8m', type: 'quiz' },
      { id: 's2_ux_t1', title: 'Task: Redesigning LinkedIn\'s Sign-Up Experience — End to End', type: 'task' },
    ],
  },

  {
    id: 's2_ui_capsule',
    sprint: 2,
    sprintName: 'Flutter Development Essentials',
    track: 'Quality',
    title: 'UI in a Capsule',
    totalTopicsCount: 79,
    totalDurationText: '3h 30m',
    taskName: 'Real-World Visual Design: From UI Conventions to Developer Handoff',
    isTask: true,
    isCapstone: false,
    badges: ['task-required', 'micro-learning'],
    lessons: [
      { id: 's2_ui_01', title: 'Visual Design Fundamentals — Hierarchy & Balance', duration: '8m 00s', type: 'video' },
      { id: 's2_ui_02', title: 'Gestalt Principles — Proximity, Similarity, Closure', duration: '9m 30s', type: 'video' },
      { id: 's2_ui_03', title: 'Color Theory — HSL, Complementary & Triadic', duration: '10m 45s', type: 'video' },
      { id: 's2_ui_04', title: 'Semantic Color Systems & Design Tokens', duration: '8m 15s', type: 'video' },
      { id: 's2_ui_05', title: 'Typography — Type Scale, Pairing & Line Height', duration: '9m 00s', type: 'video' },
      { id: 's2_ui_06', title: 'F-Pattern, Z-Pattern & Grid Layouts', duration: '7m 30s', type: 'video' },
      { id: 's2_ui_07', title: 'Mobile Gesture Vocabulary — Tap, Swipe, Pinch', duration: '6m 45s', type: 'video' },
      { id: 's2_ui_08', title: 'Building Component Libraries in Figma', duration: '12m 00s', type: 'video' },
      { id: 's2_ui_09', title: 'Design Systems & Tokens Management', duration: '10m 15s', type: 'video' },
      { id: 's2_ui_10', title: 'Dev Handoff — Figma Dev Mode & Zeplin', duration: '9m 30s', type: 'video' },
      { id: 's2_ui_11', title: 'Dark Mode & Theming Strategies', duration: '7m 00s', type: 'video' },
      { id: 's2_ui_q1', title: 'Quiz: Visual Design Principles', duration: '8m', type: 'quiz' },
      { id: 's2_ui_t1', title: 'Task: Real-World Visual Design: From UI Conventions to Developer Handoff', type: 'task' },
    ],
  },

  {
    id: 's2_mobile_intro',
    sprint: 2,
    sprintName: 'Flutter Development Essentials',
    track: 'Mobile',
    title: 'Introduction to Mobile Development',
    totalTopicsCount: 15,
    totalDurationText: '55m',
    taskName: 'Mobile Architecture Recommendation: Native, Web & Cross-Platform Strategies',
    isTask: true,
    isCapstone: false,
    badges: ['task-required', 'micro-learning'],
    lessons: [
      { id: 's2_mob_01', title: 'Mobile Ecosystem Overview — iOS & Android', duration: '5m 30s', type: 'video' },
      { id: 's2_mob_02', title: 'Native Development — Swift & Kotlin Pros/Cons', duration: '7m 00s', type: 'video' },
      { id: 's2_mob_03', title: 'Web Apps & PWAs — Browser-Based Mobile', duration: '5m 45s', type: 'video' },
      { id: 's2_mob_04', title: 'Cross-Platform Frameworks — Flutter vs RN vs Ionic', duration: '8m 30s', type: 'video' },
      { id: 's2_mob_05', title: 'Flutter Architecture — Dart VM & Rendering Engine', duration: '9m 15s', type: 'video' },
      { id: 's2_mob_06', title: 'Android & iOS App Lifecycle Overview', duration: '6m 00s', type: 'video' },
      { id: 's2_mob_07', title: 'APK vs IPA — Build & Distribution Pipeline', duration: '5m 30s', type: 'video' },
      { id: 's2_mob_q1', title: 'Quiz: Mobile Architecture Fundamentals', duration: '5m', type: 'quiz' },
      { id: 's2_mob_t1', title: 'Task: Mobile Architecture Recommendation', type: 'task' },
    ],
  },

  {
    id: 's2_dart_essentials',
    sprint: 2,
    sprintName: 'Flutter Development Essentials',
    track: 'Mobile',
    title: 'Dart Essentials',
    totalTopicsCount: 50,
    totalDurationText: '3h 20m',
    taskName: 'Object-Oriented User Management Architecture with Mock JSON Data',
    isTask: true,
    isCapstone: false,
    prerequisites: ['s2_mobile_intro'],
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's2_dart_01', title: 'Dart Language Overview & Setup', duration: '5m 00s', type: 'video' },
      { id: 's2_dart_02', title: 'Variables — var, final, const & Type Inference', duration: '7m 30s', type: 'video' },
      { id: 's2_dart_03', title: 'Built-in Types — int, double, String, bool', duration: '6m 45s', type: 'video' },
      { id: 's2_dart_04', title: 'Null Safety — ?, !, late & Required', duration: '9m 00s', type: 'video' },
      { id: 's2_dart_05', title: 'Collections — List, Map, Set & Spread Operators', duration: '10m 30s', type: 'video' },
      { id: 's2_dart_06', title: 'Control Flow — if/else, switch, for, while', duration: '8m 00s', type: 'video' },
      { id: 's2_dart_07', title: 'Functions — Named, Optional & Arrow Syntax', duration: '9m 15s', type: 'video' },
      { id: 's2_dart_08', title: 'Higher-Order Functions — map, where, reduce', duration: '8m 30s', type: 'video' },
      { id: 's2_dart_09', title: 'OOP — Classes, Constructors & Getters/Setters', duration: '11m 00s', type: 'video' },
      { id: 's2_dart_10', title: 'Inheritance, Abstract Classes & Interfaces', duration: '10m 45s', type: 'video' },
      { id: 's2_dart_11', title: 'Mixins, Enums & Generics', duration: '9m 30s', type: 'video' },
      { id: 's2_dart_12', title: 'Async/Await, Futures & Error Handling', duration: '11m 00s', type: 'video' },
      { id: 's2_dart_q1', title: 'Quiz: Dart Language Fundamentals', duration: '10m', type: 'quiz' },
      { id: 's2_dart_t1', title: 'Task: OOP User Management with Mock JSON', type: 'task' },
    ],
  },

  {
    id: 's2_flutter_fundamentals',
    sprint: 2,
    sprintName: 'Flutter Development Essentials',
    track: 'Mobile',
    title: 'Flutter Fundamentals',
    totalTopicsCount: 72,
    totalDurationText: '5h 10m',
    taskName: 'Flutter Shopping App — Mini Project',
    isTask: true,
    isCapstone: false,
    prerequisites: ['s2_dart_essentials'],
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's2_flt_01', title: 'Flutter SDK Setup & First App', duration: '8m 00s', type: 'video' },
      { id: 's2_flt_02', title: 'Widget Tree, Element Tree & Render Tree', duration: '10m 30s', type: 'video' },
      { id: 's2_flt_03', title: 'Stateless Widgets — Structure & Best Practices', duration: '7m 45s', type: 'video' },
      { id: 's2_flt_04', title: 'Stateful Widgets — initState, setState, dispose', duration: '9m 15s', type: 'video' },
      { id: 's2_flt_05', title: 'Layout Widgets — Column, Row, Stack, Expanded', duration: '11m 00s', type: 'video' },
      { id: 's2_flt_06', title: 'MaterialApp, ThemeData & ColorScheme', duration: '8m 30s', type: 'video' },
      { id: 's2_flt_07', title: 'Text, Image, Icon & Button Widgets', duration: '7m 00s', type: 'video' },
      { id: 's2_flt_08', title: 'ListView, GridView & Slivers', duration: '10m 45s', type: 'video' },
      { id: 's2_flt_09', title: 'TextFormField, Forms & Validation', duration: '9m 30s', type: 'video' },
      { id: 's2_flt_10', title: 'Navigator 2.0 & go_router Setup', duration: '12m 00s', type: 'video' },
      { id: 's2_flt_11', title: 'Named Routes, Deep Links & Route Guards', duration: '9m 00s', type: 'video' },
      { id: 's2_flt_12', title: 'Implicit Animations — AnimatedContainer, AnimatedOpacity', duration: '8m 15s', type: 'video' },
      { id: 's2_flt_13', title: 'Explicit Animations — AnimationController & Tween', duration: '10m 30s', type: 'video' },
      { id: 's2_flt_14', title: 'Hero Animations & Page Transitions', duration: '7m 45s', type: 'video' },
      { id: 's2_flt_15', title: 'Localization — ARB Files & intl Package', duration: '8m 00s', type: 'video' },
      { id: 's2_flt_16', title: 'Semantics & Screen Reader Accessibility', duration: '6m 30s', type: 'video' },
      { id: 's2_flt_q1', title: 'Quiz: Flutter Widget Lifecycle & Navigation', duration: '10m', type: 'quiz' },
      { id: 's2_flt_t1', title: 'Task: Flutter Shopping App Mini Project', type: 'task' },
    ],
  },

  {
    id: 's2_capstone',
    sprint: 2,
    sprintName: 'Flutter Development Essentials',
    track: 'Mobile',
    title: '🏆 Capstone: End-to-End Flutter E-Commerce App',
    totalTopicsCount: 6,
    totalDurationText: '10h',
    isTask: false,
    isCapstone: true,
    badges: ['capstone', 'high-energy'],
    lessons: [
      { id: 's2_cap_01', title: 'Project Brief & Architecture Design Session', duration: '20m', type: 'video' },
      { id: 's2_cap_02', title: 'Build Product Listing with REST API', type: 'lab' },
      { id: 's2_cap_03', title: 'Cart & Checkout Flow with Local State', type: 'lab' },
      { id: 's2_cap_04', title: 'User Authentication & Session Management', type: 'lab' },
      { id: 's2_cap_05', title: 'Polish, Animations & Responsive Layout', type: 'lab' },
      { id: 's2_cap_06', title: 'Final Demo, Code Review & Submission', type: 'capstone' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPRINT 3 — Advanced Mobile Development (6h 49m) | Mobile Track
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 's3_data_handling',
    sprint: 3,
    sprintName: 'Advanced Mobile Development',
    track: 'Mobile',
    title: 'Data Handling & Local/Remote APIs',
    totalTopicsCount: 35,
    totalDurationText: '2h 00m',
    taskName: 'Flutter Data Handling — Mini Project',
    isTask: true,
    isCapstone: false,
    prerequisites: ['s2_flutter_fundamentals'],
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's3_dat_01', title: 'pubspec.yaml Deep Dive & Semantic Versioning', duration: '6m 30s', type: 'video' },
      { id: 's3_dat_02', title: 'Popular Packages Survey — Top 20 Flutter Libs', duration: '5m 00s', type: 'video' },
      { id: 's3_dat_03', title: 'Google Maps Flutter — Embed & Markers', duration: '10m 00s', type: 'video' },
      { id: 's3_dat_04', title: 'Geolocator — GPS & LocationSettings', duration: '8m 30s', type: 'video' },
      { id: 's3_dat_05', title: 'HTTP Package Basics — GET, POST, Error Handling', duration: '9m 15s', type: 'video' },
      { id: 's3_dat_06', title: 'Dio — Interceptors, BaseOptions & Retry Logic', duration: '11m 00s', type: 'video' },
      { id: 's3_dat_07', title: 'JSON Parsing — json_serializable & Freezed', duration: '9m 30s', type: 'video' },
      { id: 's3_dat_08', title: 'SharedPreferences for Key-Value Storage', duration: '6m 00s', type: 'video' },
      { id: 's3_dat_09', title: 'Hive — TypeAdapters, Boxes & Encrypted Storage', duration: '10m 45s', type: 'video' },
      { id: 's3_dat_10', title: 'Cache-First & Stale-While-Revalidate Strategies', duration: '8m 00s', type: 'video' },
      { id: 's3_dat_q1', title: 'Quiz: Networking & Caching Patterns', duration: '6m', type: 'quiz' },
      { id: 's3_dat_t1', title: 'Task: Flutter Data Handling Mini Project', type: 'task' },
    ],
  },

  {
    id: 's3_state_management',
    sprint: 3,
    sprintName: 'Advanced Mobile Development',
    track: 'Mobile',
    title: 'State Management with BLoC',
    totalTopicsCount: 29,
    totalDurationText: '1h 35m',
    taskName: 'Flutter State Management — Mini Project',
    isTask: true,
    isCapstone: false,
    prerequisites: ['s2_flutter_fundamentals'],
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's3_blc_01', title: 'Why State Management? The Problem with setState', duration: '5m 30s', type: 'video' },
      { id: 's3_blc_02', title: 'Dart Streams & StreamControllers', duration: '9m 00s', type: 'video' },
      { id: 's3_blc_03', title: 'BLoC Architecture — Events, States & Bloc Class', duration: '11m 30s', type: 'video' },
      { id: 's3_blc_04', title: 'flutter_bloc Setup — BlocProvider & BlocBuilder', duration: '9m 15s', type: 'video' },
      { id: 's3_blc_05', title: 'BlocListener & BlocConsumer — Side Effects', duration: '8m 45s', type: 'video' },
      { id: 's3_blc_06', title: 'Cubit — Lightweight BLoC Alternative', duration: '7m 30s', type: 'video' },
      { id: 's3_blc_07', title: 'HydratedCubit — Persisting State Across Sessions', duration: '8m 00s', type: 'video' },
      { id: 's3_blc_08', title: 'MultiBlocProvider & Cubit Composition', duration: '6m 30s', type: 'video' },
      { id: 's3_blc_09', title: 'Provider Package — Consumer & context.watch()', duration: '8m 15s', type: 'video' },
      { id: 's3_blc_q1', title: 'Quiz: BLoC vs Cubit vs Provider', duration: '6m', type: 'quiz' },
      { id: 's3_blc_t1', title: 'Task: Flutter State Management Mini Project', type: 'task' },
    ],
  },

  {
    id: 's3_firebase',
    sprint: 3,
    sprintName: 'Advanced Mobile Development',
    track: 'Mobile',
    title: 'Firebase Integration',
    totalTopicsCount: 25,
    totalDurationText: '1h 20m',
    taskName: 'Flutter Firebase — Mini Project',
    isTask: true,
    isCapstone: false,
    prerequisites: ['s2_flutter_fundamentals'],
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's3_fir_01', title: 'FlutterFire CLI — Project Setup & Configuration', duration: '7m 30s', type: 'video' },
      { id: 's3_fir_02', title: 'Firebase Auth — Email/Password Sign-Up & Login', duration: '9m 00s', type: 'video' },
      { id: 's3_fir_03', title: 'Google Sign-In & Apple Sign-In', duration: '8m 15s', type: 'video' },
      { id: 's3_fir_04', title: 'Phone OTP Authentication', duration: '7m 00s', type: 'video' },
      { id: 's3_fir_05', title: 'Auth State Streams & User Persistence', duration: '6m 30s', type: 'video' },
      { id: 's3_fir_06', title: 'Firestore Data Model — Collections & Documents', duration: '8m 45s', type: 'video' },
      { id: 's3_fir_07', title: 'CRUD Operations & Real-Time Snapshots', duration: '9m 30s', type: 'video' },
      { id: 's3_fir_08', title: 'Compound Queries, Ordering & Pagination', duration: '7m 45s', type: 'video' },
      { id: 's3_fir_09', title: 'Firestore Security Rules — Basics & Testing', duration: '8m 00s', type: 'video' },
      { id: 's3_fir_q1', title: 'Quiz: Firebase Auth & Firestore', duration: '5m', type: 'quiz' },
      { id: 's3_fir_t1', title: 'Task: Flutter Firebase Mini Project', type: 'task' },
    ],
  },

  {
    id: 's3_device_features',
    sprint: 3,
    sprintName: 'Advanced Mobile Development',
    track: 'Mobile',
    title: 'Access Device Features',
    totalTopicsCount: 34,
    totalDurationText: '1h 45m',
    taskName: 'Flutter Device Features — Mini Project',
    isTask: true,
    isCapstone: false,
    prerequisites: ['s2_flutter_fundamentals'],
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's3_dev_01', title: 'permission_handler — Requesting & Managing Permissions', duration: '7m 00s', type: 'video' },
      { id: 's3_dev_02', title: 'Image Picker — Gallery & Camera Integration', duration: '8m 30s', type: 'video' },
      { id: 's3_dev_03', title: 'Video Player & Audio Recording', duration: '9m 00s', type: 'video' },
      { id: 's3_dev_04', title: 'sensors_plus — Accelerometer, Gyroscope & Magnetometer', duration: '8m 15s', type: 'video' },
      { id: 's3_dev_05', title: 'Biometrics — local_auth Fingerprint & Face ID', duration: '7m 30s', type: 'video' },
      { id: 's3_dev_06', title: 'Bluetooth & BLE Connectivity', duration: '9m 45s', type: 'video' },
      { id: 's3_dev_07', title: 'NFC — Reading & Writing Tags', duration: '7m 00s', type: 'video' },
      { id: 's3_dev_08', title: 'Camera Package — CameraController & Capture', duration: '9m 30s', type: 'video' },
      { id: 's3_dev_09', title: 'Push Notifications with FCM', duration: '8m 45s', type: 'video' },
      { id: 's3_dev_q1', title: 'Quiz: Device Features & Permissions', duration: '5m', type: 'quiz' },
      { id: 's3_dev_t1', title: 'Task: Flutter Device Features Mini Project', type: 'task' },
    ],
  },

  {
    id: 's3_design_patterns',
    sprint: 3,
    sprintName: 'Advanced Mobile Development',
    track: 'Mobile',
    title: 'Design Patterns & Clean Architecture',
    totalTopicsCount: 41,
    totalDurationText: '2h 10m',
    taskName: 'Flutter Design Patterns & Clean Architecture — Mini Project',
    isTask: true,
    isCapstone: false,
    prerequisites: ['s3_state_management', 's3_data_handling'],
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's3_arc_01', title: 'SOLID Principles — SRP, OCP, LSP, ISP, DIP in Dart', duration: '12m 00s', type: 'video' },
      { id: 's3_arc_02', title: 'Creational Patterns — Singleton, Factory & Builder', duration: '10m 30s', type: 'video' },
      { id: 's3_arc_03', title: 'Structural Patterns — Adapter, Decorator & Facade', duration: '9m 45s', type: 'video' },
      { id: 's3_arc_04', title: 'Behavioral Patterns — Observer, Strategy & Command', duration: '10m 15s', type: 'video' },
      { id: 's3_arc_05', title: 'Clean Architecture Overview — Why It Matters', duration: '8m 30s', type: 'video' },
      { id: 's3_arc_06', title: 'Domain Layer — Entities & Use Cases', duration: '9m 00s', type: 'video' },
      { id: 's3_arc_07', title: 'Data Layer — Repositories & Data Sources', duration: '10m 00s', type: 'video' },
      { id: 's3_arc_08', title: 'Presentation Layer — BLoC + UI', duration: '8m 45s', type: 'video' },
      { id: 's3_arc_09', title: 'Dependency Injection — get_it & injectable', duration: '9m 30s', type: 'video' },
      { id: 's3_arc_10', title: 'Feature-First Folder Structure', duration: '6m 30s', type: 'video' },
      { id: 's3_arc_q1', title: 'Quiz: Clean Architecture & Design Patterns', duration: '8m', type: 'quiz' },
      { id: 's3_arc_t1', title: 'Task: Flutter Design Patterns & Clean Architecture Mini Project', type: 'task' },
    ],
  },

  {
    id: 's3_capstone',
    sprint: 3,
    sprintName: 'Advanced Mobile Development',
    track: 'Mobile',
    title: '🏆 Capstone: Flutter Community App — Architecture, Native Features & Beta',
    totalTopicsCount: 6,
    totalDurationText: '12h',
    isTask: false,
    isCapstone: true,
    badges: ['capstone', 'high-energy'],
    lessons: [
      { id: 's3_cap_01', title: 'Capstone Brief & Architecture Planning', duration: '20m', type: 'video' },
      { id: 's3_cap_02', title: 'Real-Time Feed with Firestore & BLoC', type: 'lab' },
      { id: 's3_cap_03', title: 'Image Upload, Camera & Media Features', type: 'lab' },
      { id: 's3_cap_04', title: 'User Profiles, Auth & Notifications', type: 'lab' },
      { id: 's3_cap_05', title: 'Clean Architecture Refactor & Testing', type: 'lab' },
      { id: 's3_cap_06', title: 'Beta Release, APK Build & Submission', type: 'capstone' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPRINT 4 — Mobile Deployment & Testing (6h 58m) | Systems + QA + Mobile
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 's4_docker',
    sprint: 4,
    sprintName: 'Mobile Deployment & Testing',
    track: 'Systems',
    title: 'Containerization Essentials',
    totalTopicsCount: 52,
    totalDurationText: '3h 00m',
    taskName: 'End-to-End Docker Image Lifecycle for a Flask App',
    isTask: true,
    isCapstone: false,
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's4_dkr_01', title: 'Virtualization vs Containerization — Core Differences', duration: '7m 30s', type: 'video' },
      { id: 's4_dkr_02', title: 'Docker Architecture — Daemon, Client & Registry', duration: '9m 00s', type: 'video' },
      { id: 's4_dkr_03', title: 'Installing Docker Desktop & CLI Verification', duration: '6m 15s', type: 'video' },
      { id: 's4_dkr_04', title: 'Core Docker Commands — pull, run, ps, stop, rm', duration: '8m 30s', type: 'video' },
      { id: 's4_dkr_05', title: 'Dockerfile Syntax — FROM, RUN, COPY, EXPOSE, CMD', duration: '11m 00s', type: 'video' },
      { id: 's4_dkr_06', title: 'Image Layers & Build Cache Optimization', duration: '9m 45s', type: 'video' },
      { id: 's4_dkr_07', title: 'Multi-Stage Builds — Reducing Image Size', duration: '8m 30s', type: 'video' },
      { id: 's4_dkr_08', title: 'docker-compose — Multi-Container Applications', duration: '12m 00s', type: 'video' },
      { id: 's4_dkr_09', title: 'Volumes & Persistent Storage', duration: '8m 15s', type: 'video' },
      { id: 's4_dkr_10', title: 'Docker Networks — Bridge, Host & Custom', duration: '7m 30s', type: 'video' },
      { id: 's4_dkr_11', title: 'Health Checks & Environment Variables', duration: '6m 45s', type: 'video' },
      { id: 's4_dkr_12', title: 'Pushing to Docker Hub & Registry Basics', duration: '7m 00s', type: 'video' },
      { id: 's4_dkr_q1', title: 'Quiz: Docker Architecture & Commands', duration: '8m', type: 'quiz' },
      { id: 's4_dkr_t1', title: 'Task: End-to-End Docker Image Lifecycle for a Flask App', type: 'task' },
    ],
  },

  {
    id: 's4_manual_testing',
    sprint: 4,
    sprintName: 'Mobile Deployment & Testing',
    track: 'Quality',
    title: 'Practical Mobile Testing',
    totalTopicsCount: 55,
    totalDurationText: '2h 30m',
    taskName: 'Mobile Application Testing — Mini Task',
    isTask: true,
    isCapstone: false,
    badges: ['task-required', 'micro-learning'],
    lessons: [
      { id: 's4_tst_01', title: 'STLC Overview — Planning to Closure', duration: '7m 00s', type: 'video' },
      { id: 's4_tst_02', title: 'Testing Levels — Unit, Integration, System, UAT', duration: '9m 30s', type: 'video' },
      { id: 's4_tst_03', title: 'Testing Types — Functional, Regression, Smoke, Sanity', duration: '8m 15s', type: 'video' },
      { id: 's4_tst_04', title: 'Writing Effective Test Cases — ID, Priority, Steps', duration: '10m 00s', type: 'video' },
      { id: 's4_tst_05', title: 'Equivalence Partitioning & Boundary Value Analysis', duration: '8m 45s', type: 'video' },
      { id: 's4_tst_06', title: 'Bug Lifecycle — Open → Assigned → Fixed → Closed', duration: '7m 00s', type: 'video' },
      { id: 's4_tst_07', title: 'Jira Workflow — Backlog, Sprints & Bug Reports', duration: '9m 30s', type: 'video' },
      { id: 's4_tst_08', title: 'Requirements Traceability Matrix (RTM)', duration: '8m 00s', type: 'video' },
      { id: 's4_tst_09', title: 'Exploratory Testing Techniques', duration: '6m 30s', type: 'video' },
      { id: 's4_tst_10', title: 'Mobile-Specific Testing — Gestures, Orientations, OS Versions', duration: '8m 15s', type: 'video' },
      { id: 's4_tst_q1', title: 'Quiz: STLC & Test Case Design', duration: '8m', type: 'quiz' },
      { id: 's4_tst_t1', title: 'Task: Mobile Application Testing Mini Task', type: 'task' },
    ],
  },

  {
    id: 's4_automation_appium',
    sprint: 4,
    sprintName: 'Mobile Deployment & Testing',
    track: 'Quality',
    title: 'Mobile Testing Automation with Appium',
    totalTopicsCount: 33,
    totalDurationText: '1h 55m',
    taskName: 'Mobile Testing Automation with Appium — Mini Task',
    isTask: true,
    isCapstone: false,
    prerequisites: ['s4_manual_testing'],
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's4_apm_01', title: 'Appium Architecture — Server, Client & Drivers', duration: '7m 30s', type: 'video' },
      { id: 's4_apm_02', title: 'Windows & Android Emulator Setup', duration: '10m 00s', type: 'video' },
      { id: 's4_apm_03', title: 'Appium Inspector — Element Identification', duration: '9m 15s', type: 'video' },
      { id: 's4_apm_04', title: 'UIAutomator2 Driver & Desired Capabilities', duration: '8m 30s', type: 'video' },
      { id: 's4_apm_05', title: 'Writing Your First Automated Test', duration: '11m 00s', type: 'video' },
      { id: 's4_apm_06', title: 'W3C Actions API — Tap, Long Press, Swipe', duration: '9m 45s', type: 'video' },
      { id: 's4_apm_07', title: 'Page Object Model (POM) Design Pattern', duration: '10m 30s', type: 'video' },
      { id: 's4_apm_08', title: 'TestNG — Test Suite & Parallel Execution', duration: '8m 15s', type: 'video' },
      { id: 's4_apm_09', title: 'Allure Reporting & CI Integration Basics', duration: '7m 00s', type: 'video' },
      { id: 's4_apm_q1', title: 'Appium Java Quick Reference Sheet', duration: '5m', type: 'capsule' },
      { id: 's4_apm_t1', title: 'Task: Mobile Testing Automation with Appium Mini Task', type: 'task' },
    ],
  },

  {
    id: 's4_capstone_qa',
    sprint: 4,
    sprintName: 'Mobile Deployment & Testing',
    track: 'Quality',
    title: '🏆 Capstone: End-to-End Mobile Testing — Manual QA & Appium Suite',
    totalTopicsCount: 5,
    totalDurationText: '8h',
    isTask: false,
    isCapstone: true,
    badges: ['capstone', 'high-energy'],
    lessons: [
      { id: 's4_qac_01', title: 'QA Capstone Brief & Test Planning', duration: '15m', type: 'video' },
      { id: 's4_qac_02', title: '50+ Test Case Design for Flutter App', type: 'lab' },
      { id: 's4_qac_03', title: 'Manual Test Execution & Jira Bug Reports', type: 'lab' },
      { id: 's4_qac_04', title: 'Appium Automation Suite — Login, Cart, Navigation', type: 'lab' },
      { id: 's4_qac_05', title: 'Allure Report Submission & Peer Review', type: 'capstone' },
    ],
  },

  {
    id: 's4_graduation_capstone',
    sprint: 4,
    sprintName: 'Mobile Deployment & Testing',
    track: 'Mobile',
    title: '🎓 Graduation Capstone: StreetBite — Hyperlocal Food Discovery & Ordering',
    totalTopicsCount: 8,
    totalDurationText: '20h',
    isTask: false,
    isCapstone: true,
    badges: ['capstone', 'high-energy'],
    lessons: [
      { id: 's4_sb_01', title: 'StreetBite Brief — Vision, Scope & Deliverables', duration: '25m', type: 'video' },
      { id: 's4_sb_02', title: 'Clean Architecture Setup & Folder Structure', type: 'lab' },
      { id: 's4_sb_03', title: 'Firebase Auth + Firestore + Storage Integration', type: 'lab' },
      { id: 's4_sb_04', title: 'Google Maps — Restaurant Discovery & Location', type: 'lab' },
      { id: 's4_sb_05', title: 'Food Ordering Pipeline & Cart with BLoC', type: 'lab' },
      { id: 's4_sb_06', title: 'Rating System, Reviews & Real-Time Updates', type: 'lab' },
      { id: 's4_sb_07', title: 'Delivery Tracking Screen & Status Animations', type: 'lab' },
      { id: 's4_sb_08', title: 'APK Build, Demo & Final Submission', type: 'capstone' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPRINT 5 — Delivery, Leadership & Career Readiness (17h 37m) | Career Track
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 's5_design_thinking',
    sprint: 5,
    sprintName: 'Delivery, Leadership & Career Readiness',
    track: 'Career',
    title: 'Design Thinking',
    totalTopicsCount: 34,
    totalDurationText: '1h 45m',
    isTask: false,
    isCapstone: false,
    badges: ['micro-learning'],
    lessons: [
      { id: 's5_dt_01', title: 'Stanford d.school Design Thinking Framework', duration: '7m 30s', type: 'video' },
      { id: 's5_dt_02', title: 'Empathize — User Research & Persona Building', duration: '9m 00s', type: 'video' },
      { id: 's5_dt_03', title: 'Define — Problem Statement & HMW Questions', duration: '7m 15s', type: 'video' },
      { id: 's5_dt_04', title: 'Ideate — Brainstorming & Concept Generation', duration: '8m 30s', type: 'video' },
      { id: 's5_dt_05', title: 'Prototype — Low & High Fidelity Approaches', duration: '7m 00s', type: 'video' },
      { id: 's5_dt_06', title: 'Test — Usability Testing & Iteration', duration: '6m 45s', type: 'video' },
      { id: 's5_dt_07', title: 'Product-Market Fit & Value Proposition', duration: '8m 15s', type: 'video' },
      { id: 's5_dt_08', title: 'AI for User Empathy & Research Synthesis', duration: '9m 00s', type: 'video' },
      { id: 's5_dt_09', title: 'Jobs-To-Be-Done (JTBD) Theory', duration: '7m 30s', type: 'video' },
    ],
  },

  {
    id: 's5_business_etiquette',
    sprint: 5,
    sprintName: 'Delivery, Leadership & Career Readiness',
    track: 'Career',
    title: 'Business Etiquette & Job Hunt',
    totalTopicsCount: 17,
    totalDurationText: '55m',
    isTask: false,
    isCapstone: false,
    badges: ['micro-learning'],
    lessons: [
      { id: 's5_be_01', title: 'Professional Email — Structure, Tone & Subject Lines', duration: '6m 30s', type: 'video' },
      { id: 's5_be_02', title: 'Meeting Etiquette — Preparation & Follow-ups', duration: '5m 45s', type: 'video' },
      { id: 's5_be_03', title: 'Remote Work Norms — Slack, Camera Culture & Async', duration: '6m 00s', type: 'video' },
      { id: 's5_be_04', title: 'Cross-Functional Team Communication', duration: '5m 30s', type: 'video' },
      { id: 's5_be_05', title: 'Job Application Phase — ATS, Platforms & Timing', duration: '7m 00s', type: 'video' },
      { id: 's5_be_06', title: 'Interview Conduct — Before, During & After', duration: '6m 15s', type: 'video' },
      { id: 's5_be_07', title: 'Handling Rejection & Negotiation Basics', duration: '5m 45s', type: 'video' },
    ],
  },

  {
    id: 's5_communication',
    sprint: 5,
    sprintName: 'Delivery, Leadership & Career Readiness',
    track: 'Career',
    title: 'Communication Skills',
    totalTopicsCount: 49,
    totalDurationText: '2h 20m',
    isTask: false,
    isCapstone: false,
    badges: ['micro-learning'],
    lessons: [
      { id: 's5_com_01', title: 'Shannon-Weaver Communication Model', duration: '6m 00s', type: 'video' },
      { id: 's5_com_02', title: 'Ethos, Pathos & Logos — Persuasion Framework', duration: '7m 30s', type: 'video' },
      { id: 's5_com_03', title: 'DISC Profiles — Dominance, Influence, Steadiness, Conscientiousness', duration: '9m 45s', type: 'video' },
      { id: 's5_com_04', title: 'Identifying Your DISC Style & Adapting', duration: '8m 00s', type: 'video' },
      { id: 's5_com_05', title: 'Active Listening — Techniques & Pitfalls', duration: '7m 15s', type: 'video' },
      { id: 's5_com_06', title: 'Constructive Feedback — SBI & STAR Frameworks', duration: '9m 30s', type: 'video' },
      { id: 's5_com_07', title: 'Assertive vs Aggressive vs Passive Communication', duration: '7m 45s', type: 'video' },
      { id: 's5_com_08', title: 'Difficult Conversations — Conflict Resolution', duration: '8m 30s', type: 'video' },
      { id: 's5_com_09', title: 'Non-Verbal Communication & Body Language', duration: '6m 45s', type: 'video' },
      { id: 's5_com_q1', title: 'Quiz: Communication Styles & DISC', duration: '6m', type: 'quiz' },
    ],
  },

  {
    id: 's5_presentation',
    sprint: 5,
    sprintName: 'Delivery, Leadership & Career Readiness',
    track: 'Career',
    title: 'Presentation Skills',
    totalTopicsCount: 37,
    totalDurationText: '1h 50m',
    isTask: false,
    isCapstone: false,
    badges: ['micro-learning'],
    lessons: [
      { id: 's5_pre_01', title: 'The Pyramid Principle — Structure for Clarity', duration: '7m 30s', type: 'video' },
      { id: 's5_pre_02', title: 'Rule of 3 & Storytelling with Data', duration: '8m 00s', type: 'video' },
      { id: 's5_pre_03', title: 'Slide Design for Technical Presentations', duration: '9m 15s', type: 'video' },
      { id: 's5_pre_04', title: 'Body Language — Posture, Eye Contact & Movement', duration: '7m 45s', type: 'video' },
      { id: 's5_pre_05', title: 'Vocal Variety — Pace, Pitch, Pause & Tone', duration: '8m 30s', type: 'video' },
      { id: 's5_pre_06', title: 'Audience Analysis & Content Structuring', duration: '7m 00s', type: 'video' },
      { id: 's5_pre_07', title: 'Handling Q&A Sessions Confidently', duration: '6m 45s', type: 'video' },
      { id: 's5_pre_08', title: 'Presenting Technical Work to Non-Technical Stakeholders', duration: '8m 15s', type: 'video' },
    ],
  },

  {
    id: 's5_project_management',
    sprint: 5,
    sprintName: 'Delivery, Leadership & Career Readiness',
    track: 'Career',
    title: 'Project Management Fundamentals',
    totalTopicsCount: 34,
    totalDurationText: '1h 45m',
    isTask: false,
    isCapstone: false,
    badges: ['micro-learning'],
    lessons: [
      { id: 's5_pm_01', title: 'Project Management Knowledge Areas — PMBoK Overview', duration: '7m 00s', type: 'video' },
      { id: 's5_pm_02', title: 'Triple Constraint — Scope, Time & Cost', duration: '6m 30s', type: 'video' },
      { id: 's5_pm_03', title: 'Risk Matrix — Probability × Impact', duration: '8m 15s', type: 'video' },
      { id: 's5_pm_04', title: 'Risk Response Strategies — Avoid, Transfer, Mitigate', duration: '7m 00s', type: 'video' },
      { id: 's5_pm_05', title: 'Earned Value Management — PV, EV, AC, SPI, CPI', duration: '10m 30s', type: 'video' },
      { id: 's5_pm_06', title: 'Lead Time & Cycle Time in Software Teams', duration: '6m 45s', type: 'video' },
      { id: 's5_pm_07', title: 'Burn-Up vs Burn-Down Charts', duration: '7m 30s', type: 'video' },
      { id: 's5_pm_08', title: 'RAID Log — Risks, Assumptions, Issues, Dependencies', duration: '6m 00s', type: 'video' },
    ],
  },

  {
    id: 's5_agile_scrum',
    sprint: 5,
    sprintName: 'Delivery, Leadership & Career Readiness',
    track: 'Career',
    title: 'Agile & Scrum Mastery',
    totalTopicsCount: 50,
    totalDurationText: '2h 30m',
    isTask: false,
    isCapstone: false,
    badges: ['micro-learning'],
    lessons: [
      { id: 's5_agile_01', title: 'Agile Manifesto — 4 Values & 12 Principles', duration: '7m 30s', type: 'video' },
      { id: 's5_agile_02', title: 'Scrum Roles — Product Owner, Scrum Master, Dev Team', duration: '8m 00s', type: 'video' },
      { id: 's5_agile_03', title: 'Scrum Ceremonies — Planning, Standup, Review, Retro', duration: '9m 15s', type: 'video' },
      { id: 's5_agile_04', title: 'Product Backlog — Grooming & Prioritization', duration: '7m 45s', type: 'video' },
      { id: 's5_agile_05', title: 'Writing INVEST User Stories', duration: '8m 30s', type: 'video' },
      { id: 's5_agile_06', title: 'Story Points & Velocity Estimation', duration: '7m 00s', type: 'video' },
      { id: 's5_agile_07', title: 'MoSCoW Prioritization Method', duration: '6m 30s', type: 'video' },
      { id: 's5_agile_08', title: 'Kano Model — Classifying Features by Delight', duration: '7m 15s', type: 'video' },
      { id: 's5_agile_09', title: 'WSJF — Weighted Shortest Job First', duration: '8m 00s', type: 'video' },
      { id: 's5_agile_10', title: 'Scaled Agile — SAFe, LeSS & Nexus Overview', duration: '6m 45s', type: 'video' },
      { id: 's5_agile_q1', title: 'Quiz: Scrum & Agile Fundamentals', duration: '8m', type: 'quiz' },
    ],
  },

  {
    id: 's5_leadership',
    sprint: 5,
    sprintName: 'Delivery, Leadership & Career Readiness',
    track: 'Career',
    title: 'Influence & Leadership Skills',
    totalTopicsCount: 35,
    totalDurationText: '1h 45m',
    isTask: false,
    isCapstone: false,
    badges: ['micro-learning'],
    lessons: [
      { id: 's5_lead_01', title: 'Leadership vs Management — Key Differences', duration: '6m 30s', type: 'video' },
      { id: 's5_lead_02', title: 'Situational Leadership — Adapting Your Style', duration: '8m 00s', type: 'video' },
      { id: 's5_lead_03', title: 'Multigenerational Teams — Gen Z, Millennials & Gen X', duration: '7m 15s', type: 'video' },
      { id: 's5_lead_04', title: 'Upward Management — Working with Your Manager', duration: '8m 30s', type: 'video' },
      { id: 's5_lead_05', title: 'Delegation — What, When & How to Delegate', duration: '7m 45s', type: 'video' },
      { id: 's5_lead_06', title: 'Building Trust in Engineering Teams', duration: '7m 00s', type: 'video' },
      { id: 's5_lead_07', title: 'Influence Without Authority', duration: '8m 15s', type: 'video' },
      { id: 's5_lead_08', title: 'Giving & Receiving Constructive Feedback', duration: '7m 30s', type: 'video' },
    ],
  },

  {
    id: 's5_cv_writing',
    sprint: 5,
    sprintName: 'Delivery, Leadership & Career Readiness',
    track: 'Career',
    title: 'CV Writing',
    totalTopicsCount: 50,
    totalDurationText: '2h 20m',
    isTask: false,
    isCapstone: false,
    badges: ['task-required', 'micro-learning'],
    lessons: [
      { id: 's5_cv_01', title: 'How ATS Systems Parse & Score Resumes', duration: '7m 30s', type: 'video' },
      { id: 's5_cv_02', title: 'ATS Keyword Strategy — Reverse-Engineering Job Descriptions', duration: '8m 00s', type: 'video' },
      { id: 's5_cv_03', title: 'One-Page CV Structure for Engineers', duration: '9m 15s', type: 'video' },
      { id: 's5_cv_04', title: 'Writing Your Summary — 3 Sentence Formula', duration: '6m 30s', type: 'video' },
      { id: 's5_cv_05', title: 'Quantifying Impact — "Reduced load time by 40%"', duration: '8m 45s', type: 'video' },
      { id: 's5_cv_06', title: 'Technical Skills Section — Tools, Langs & Frameworks', duration: '6m 00s', type: 'video' },
      { id: 's5_cv_07', title: 'Writing Project Descriptions That Stand Out', duration: '9m 30s', type: 'video' },
      { id: 's5_cv_08', title: 'Tailoring Your CV Per Job Description', duration: '8m 15s', type: 'video' },
      { id: 's5_cv_09', title: '10 Common CV Mistakes & How to Fix Them', duration: '7m 00s', type: 'video' },
      { id: 's5_cv_t1', title: 'Task: Write Your ATS-Optimized Engineering CV', type: 'task' },
    ],
  },

  {
    id: 's5_linkedin',
    sprint: 5,
    sprintName: 'Delivery, Leadership & Career Readiness',
    track: 'Career',
    title: 'LinkedIn Personal Branding',
    totalTopicsCount: 37,
    totalDurationText: '1h 50m',
    isTask: false,
    isCapstone: false,
    badges: ['task-required', 'micro-learning'],
    lessons: [
      { id: 's5_li_01', title: 'LinkedIn Profile Anatomy — Headline, About & Featured', duration: '8m 30s', type: 'video' },
      { id: 's5_li_02', title: 'Writing a Magnetic Headline (Not Just Your Title)', duration: '6m 45s', type: 'video' },
      { id: 's5_li_03', title: 'The About Section — 5-Part Structure', duration: '7m 30s', type: 'video' },
      { id: 's5_li_04', title: 'Featured Section — Pinning Projects & Certifications', duration: '5m 45s', type: 'video' },
      { id: 's5_li_05', title: 'Content Strategy — Carousel Posts, Articles & Case Studies', duration: '9m 00s', type: 'video' },
      { id: 's5_li_06', title: 'Connection-Building Tactics & Outreach Templates', duration: '7m 15s', type: 'video' },
      { id: 's5_li_07', title: 'Social Selling Index (SSI) & Creator Mode', duration: '6m 30s', type: 'video' },
      { id: 's5_li_08', title: 'Engagement Rituals — Comment, React & Share Strategy', duration: '6m 00s', type: 'video' },
      { id: 's5_li_t1', title: 'Task: Optimize Your LinkedIn Profile & Post Your First Article', type: 'task' },
    ],
  },

  {
    id: 's5_interview_prep',
    sprint: 5,
    sprintName: 'Delivery, Leadership & Career Readiness',
    track: 'Career',
    title: 'Comprehensive Interview Mastery',
    totalTopicsCount: 88,
    totalDurationText: '4h 10m',
    taskName: 'Full Mock Interview — Technical & Behavioral STAR Session',
    isTask: true,
    isCapstone: false,
    badges: ['task-required', 'high-energy'],
    lessons: [
      { id: 's5_int_01', title: 'Interview Mindset — Confidence & Preparation Framework', duration: '7m 00s', type: 'video' },
      { id: 's5_int_02', title: 'Understanding Interview Stages — Phone, Technical, HR', duration: '6m 30s', type: 'video' },
      { id: 's5_int_03', title: 'The STAR Method — Situation, Task, Action, Result', duration: '9m 00s', type: 'video' },
      { id: 's5_int_04', title: 'Crafting 10 STAR Stories from Your Bootcamp Projects', duration: '12m 00s', type: 'video' },
      { id: 's5_int_05', title: 'Behavioral Q&A — "Tell me about a time..." Masterclass', duration: '10m 30s', type: 'video' },
      { id: 's5_int_06', title: 'Technical Q&A — Flutter, Dart & Mobile Architecture', duration: '14m 00s', type: 'video' },
      { id: 's5_int_07', title: 'Technical Q&A — SQL, Linux & Networking', duration: '12m 30s', type: 'video' },
      { id: 's5_int_08', title: 'System Design Basics for Junior Engineers', duration: '11m 00s', type: 'video' },
      { id: 's5_int_09', title: 'Salary Negotiation — Research, Anchor & Counter', duration: '9m 15s', type: 'video' },
      { id: 's5_int_10', title: 'Handling "What\'s Your Weakness?" & Tough Questions', duration: '7m 45s', type: 'video' },
      { id: 's5_int_11', title: 'Questions to Ask the Interviewer', duration: '5m 30s', type: 'video' },
      { id: 's5_int_12', title: 'Mock Interview Simulation — Flutter Technical Round', duration: '30m', type: 'lab' },
      { id: 's5_int_13', title: 'Mock Interview Simulation — HR Behavioral Round', duration: '25m', type: 'lab' },
      { id: 's5_int_q1', title: 'Quiz: STAR Framework & Interview Tactics', duration: '8m', type: 'quiz' },
      { id: 's5_int_t1', title: 'Task: Full Mock Interview — Technical & Behavioral STAR Session', type: 'task' },
    ],
  },
]

// ─── Convenience accessors ─────────────────────────────────────────────────────
export const getCurriculumByTrack = (track: string) =>
  CURRICULUM.filter((m) => m.track === track)

export const getCurriculumBySprint = (sprint: number) =>
  CURRICULUM.filter((m) => m.sprint === sprint)

export const getModuleById = (id: string) => CURRICULUM.find((m) => m.id === id)

export const TOTAL_LESSONS = CURRICULUM.reduce((acc, m) => acc + m.lessons.length, 0)
export const TOTAL_MODULES = CURRICULUM.length
export const TOTAL_HOURS = 67
